# -----------------------------------------------------------------------------
# Copyright (c) 2011 Ozmo Inc
# Released under the GNU General Public License Version 2 (GPLv2).
# -----------------------------------------------------------------------------

EXTRA_CFLAGS = -I$(src)

obj-$(CONFIG_USB_WPAN_HCD) += ozwpan.o
ozwpan-y := \
	ozmain.o \
	ozpd.o \
	ozusbsvc.o \
	ozusbsvc1.o \
	ozhcd.o \
	ozeltbuf.o \
	ozproto.o \
	ozcdev.o \
	ozurbparanoia.o
